name: CD - Deploy to Cloud Run

on:
  push:
    branches:
      - 'main'

env:
  # CORRECT: References the secrets stored in GitHub settings
  PROJECT_ID: inlaid-vehicle-465211-u3
  GAR_LOCATION: secrets.GCP_ARTIFACT_REGISTRY 
  APP_NAME: game-repo
  REGION: us-central1

jobs:
  deploy:
    name: Build, Push, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ env.GAR_LOCATION }}/${{ env.PROJECT_ID }}/${{ env.APP_NAME }}:${{ github.sha }} .
          docker push ${{ env.GAR_LOCATION }}/${{ env.PROJECT_ID }}/${{ env.APP_NAME }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.APP_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.GAR_LOCATION }}/${{ env.PROJECT_ID }}/${{ env.APP_NAME }}:${{ github.sha }}
          flags: '--allow-unauthenticated' # Use for public services