name: CD - Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: inlaid-vehicle-465211-u3
  GAR_LOCATION: us-central1-docker.pkg.dev
  APP_NAME: game-repo
  REGION: us-central1

jobs:
  deploy:
    name: Build, Push, and Deploy
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Google Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # Step 3: Authenticate Docker with Artifact Registry
      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}

      # Step 4: Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          IMAGE_PATH=${{ env.GAR_LOCATION }}/${{ env.PROJECT_ID }}/${{ env.APP_NAME }}/${{ env.APP_NAME }}:${{ github.sha }}
          echo "Building Docker image: $IMAGE_PATH"
          docker build -t $IMAGE_PATH ./game_app
          docker push $IMAGE_PATH
