name: CI - Build and Test

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install project dependencies
          pip install -r game_app/requirements.txt
          # Install flake8 for linting
          pip install flake8
          # Install pytest for tests
          pip install pytest

      - name: Lint with flake8
        run: |
          # Stop build on serious errors
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Treat all other errors as warnings
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests
        run: |
          PYTHONPATH=. pytest
